const theme = {
  dark: {
    backgroundColor: '#121216',
    border: '1px solid #121212',
    buttonBackground: '#6441a5',
    buttonColor: '#fff',
    buttonOutlineBackground: '#3a3a3d',
    buttonOutlineColor: '#fff',
    contrastColor: '#1e1e23',
    errorColor: '#f6404f',
    headerBackgroundColor: '#17171b',
    headerHeight: '50px',
    inputBackground: '#3a3a3d',
    inputColor: '#efeff1',
    menuBackgroundColor: '#1e1e23',
    menuBorder: '1px solid #121212',
    menuWidth: '220px',
    primaryColor: '#6441a5',
    textColor: '#fff',
  },
  light: {
    backgroundColor: '#f9f9f9',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    buttonBackground: '#6441a5',
    buttonColor: '#fff',
    buttonOutlineBackground: '#fff',
    buttonOutlineColor: '#6441a5',
    contrastColor: '#fff',
    errorColor: '#f6404f',
    headerBackgroundColor: '#17171b',
    headerHeight: '50px',
    inputBackground: '#fff',
    inputColor: 'rgba(0, 0, 0, 0.75)',
    menuBackgroundColor: '#fff',
    menuBorder: '1px solid rgba(0,0,0,0.1)',
    menuWidth: '220px',
    primaryColor: '#6441a5',
    textColor: 'rgba(0, 0, 0, 0.75)',
  },
}

export default theme
